title: Trevor Brunnenmeyer, PhD # your name (or website title) here
logo: "/images/New LinkedIn Profile Picture.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Using the skills developed earning a PhD in Physics to solve Data Science problems.
  <br>
  <a href="https://www.linkedin.com/in/trevor-brunnenmeyer/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-8L3KDF9KCN # your Google Analytics tracking ID here
